{% set name = "fasttext" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb03f2ef6340c6ac9e4398a30026f05471da99381b307aafe2f56e4cd26baaef

build:
  number: 1
  # pybind11 seems incompatible on win
  skip: True  # [win]
  # numpy<2 not available for py313
  skip: True  # [py>=313]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip !=25.1
    - pybind11 >=2.2
    - python
    - setuptools >=0.7.0
    - wheel
  run:
    - numpy >=1.17,<2
    - pybind11 >=2.2
    - python

test:
  requires:
    - pip
  imports:
    - fasttext
  commands:
    - pip check

about:
  home: https://fasttext.cc/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'fastText - Library for efficient text classification and representation learning'
  dev_url: https://github.com/facebookresearch/fastText
  doc_url: https://fasttext.cc/docs/en/support.html
  description: 'fastText - Library for efficient text classification and representation learning'

extra:
  recipe-maintainers:
    - JungeAlexander
    - kylebgorman
