travis:
  secure:
    BINSTAR_TOKEN: lU4jT4hx1e4VmENEPHfqoS/eWcNzY+km0n0ySYrsJYIwmTnrqeD8ddQW/nLH6MNNs5zgo4W2aQkkqs7YX5SywhG+eRToL05S1vGUtaQhjsK8JjOzsTscnDzX/r7PQB5UyoYtQy43w9evtJIm8X34BK04mgNMM9za+PKQUwnjXrKYoscXqZ08j7wPle+ApqVTYzKh/EhiRQKOnpe08EioRzbYeiZ5hG6hnCrhGRejvp4CKPqleTfcpVy5tb3mE09E70Mf32c4lRNJIeak+9i4wBDOecnlOFxoX/USIr5yqJYnvwq+Zociuxfs/OwSVYTC8T34qguYDeY2C45xB4NjoPbCu2sLIJylNgNEhhwawNWBs75uc9BJXibZuZNnadtHBaWq9Jvl4TISl/NrY/iVl795xZE57UUDcqyHlbXUvDWIaLKiXq9uvSCJMCmaVlAbJfrXl3SMF1Z9FwZeyQZ8/EwPQldwZ0Al8gJjzTF+SXFaeLW+1XZOOtwPcCemmFwt3IAJvVmDBVS9Gq5yGSYtm13Vs9mbbCy8gFv6hclNNwwPGAeAs2WTEIZWI85j8cgYa3f1LZIfZQz2f/RqYhApNV4mc8ORcIMoSOlks3gUy819B0mdLf+IyNk927x89RFJ0edOQtNiOyF7/0Dd4A2FfzbO6/cBaE4yzQGd7g9wPEg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
